### ISSUE TITLE
请问您之前MentoHUST是怎么配置的呢？

### ISSUE THREAD

**Issue by cc-SYSU** [DreamOfStars/SYSU-Network-Guide#1]
同学您好，东校目前从iNode换锐捷了，目前已经安装好了MentoHUST但不知道怎么配置，如果有经验还望分享一下

**Comment by DreamOfStars** [comment]
建议使用 [MiniEAP](https://github.com/KumaTea/minieap)，MentoHUST 我在使用过程中断连问题比较频繁
